name: Auto PR and Auto-merge on QA Done

on:
  push:
    branches:
      - 'story/**'
      - 'feature/**'
      - 'fix/**'
      - 'chore/**'
      - 'patch/**'
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch to operate on (defaults to ref name)"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write
  actions: read
  checks: read
  statuses: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  workflow-lint:
    name: Workflow Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install actionlint (pinned)
        run: |
          set -euo pipefail
          VERSION="1.7.1"
          mkdir -p "$HOME/bin"
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- "v${VERSION}" "$HOME/bin"
          echo "$HOME/bin" >> "$GITHUB_PATH"
      - name: Run actionlint (YAML only)
        run: |
          set -euo pipefail
          actionlint -shellcheck=
      - name: Install yamllint (pinned)
        run: |
          set -euo pipefail
          python3 -m pip install --user yamllint==1.35.1
      - name: Run yamllint on workflows
        run: |
          set -euo pipefail
          ~/.local/bin/yamllint --strict .github/workflows
